/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum MS_TOKEN_BINDING_ENUM {
  MS_TOKEN_BINDING_DOUBLE = 360,
  MS_TOKEN_BINDING_INTEGER,
  MS_TOKEN_BINDING_STRING,
  MS_TOKEN_BINDING_TIME,
  MS_TOKEN_BINDING_SHAPE,
  MS_TOKEN_BINDING_MAP_CELLSIZE,
  MS_TOKEN_BINDING_DATA_CELLSIZE
}
